# Generated by Django 4.2.9 on 2024-10-06 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=50)),
                ('order_date', models.DateField()),
                ('deli_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('person_name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1)),
            ],
            options={
                'verbose_name': 'Đơn mua',
                'verbose_name_plural': 'Đơn mua',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Loại hàng',
                'verbose_name_plural': 'Loại hàng',
                'db_table': 'product_type',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('provider_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=50)),
                ('person', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('acc_number', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_code', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
                'db_table': 'provider',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Đơn vị hàng hóa',
                'verbose_name_plural': 'Đơn vị hàng hóa',
                'db_table': 'units',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producttype')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit')),
            ],
            options={
                'verbose_name': 'Hàng hóa',
                'verbose_name_plural': 'Hàng hóa',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='PriceDetail',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit')),
            ],
            options={
                'verbose_name': 'Chi tiết chào giá',
                'verbose_name_plural': 'Chi tiết chào giá',
                'db_table': 'price_detail',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=255)),
                ('price_date', models.DateField()),
                ('expire', models.IntegerField(default=1)),
                ('status', models.IntegerField(choices=[(0, 'draft'), (1, 'pending'), (2, 'accepted'), (3, 'rejected')], default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provider')),
            ],
            options={
                'verbose_name': 'Chào giá',
                'verbose_name_plural': 'Chào giá',
                'db_table': 'price',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn mua',
                'verbose_name_plural': 'Chi tiết đơn mua',
                'db_table': 'order_detail',
            },
        ),
    ]
