# Generated by Django 4.2.9 on 2024-10-16 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequiredetail',
            name='buy_require',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.buyrequire', verbose_name='Mã yêu cầu mua'),
        ),
        migrations.AlterField(
            model_name='buyrequiredetail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
