from django.urls import path 
from core.views.index import index


urlpatterns = [
    path('', index, name='index'),
    path('logout/'),

    path('manager/'),
    path('manager/login'),
    path('manager/buy-require'),
    path('manager/buy-require/add'),
    path('manager/buy-require/edit/<pk:pk>'),
    path('manager/buy-require/delete/<pk:pk>'),
    path('manager/price'),
    path('manager/price/add'),
    path('manager/price/edit/<pk:pk>'),
    path('manager/price/delete/<pk:pk>'),
    path('manager/order'),
    path('manager/order/add'),
    path('manager/order/edit/<pk:pk>'),
    path('manager/order/delete/<pk:pk>'),
    path('manager/shipping'),
    path('manager/shipping/add'),
    path('manager/shipping/edit/<pk:pk>'),
    path('manager/shipping/delete/<pk:pk>'),
    path('manager/payment'),
    path('manager/payment/edit/<pk:pk>'),
    path('manager/report'),
    path('manager/report/<pk:pk>'),

    path('staff/'),
    path('staff/login'),
    path('staff/buy-require'),    
    path('staff/buy-require/add'),    
    path('staff/buy-require/edit/<pk:pk>'),    
    path('staff/buy-require/delete/<pk:pk>'),
    path('staff/price'),    
    path('staff/price/add'),    
    path('staff/price/edit/<pk:pk>'),    
    path('staff/price/delete/<pk:pk>'),
    path('staff/order'),    
    path('staff/order/add'),    
    path('staff/order/edit/<pk:pk>'),    
    path('staff/order/delete/<pk:pk>'),
    path('staff/shipping'),    
    path('staff/shipping/add'),    
    path('staff/shipping/edit/<pk:pk>'),    
    path('staff/shipping/delete/<pk:pk>'),
    path('staff/report'),    
    path('staff/report/<pk:pk>'),    
]
